### ISSUE TITLE
Planejamento

### ISSUE THREAD

**Issue by Everton42** [Cherry-Spike/biometric-auth#2]
Definir e Pesquisar     
     - [ ] Funcionalidades
     - [ ] Libs úteis
     - [ ] Framework

**Comment by danielalexsander** [comment]
boa tarde 👍

**Comment by Everton42** [comment]
Definir e Pesquisar

[ ] Funcionalidades
- CRUD Usuario / Imagem da digital
- Tela de cadastro e login
- Dashboard com informações

[ ] Libs úteis

[ ] Framework
- Spring Boot
- SQL Server/ My SQL
- **Front ?**

**Comment by Everton42** [comment]
end

**Comment by danielalexsander** [comment]
O que o trabalho pede:
    -> Pede-se aos alunos desenvolvam uma ferramenta de identificação e autenticação biométrica que restrinja o acesso a uma rede de banco de dados
        do ministério do meio ambiente
    -> As informações sao estratégicas sobre as propiedades rurais que utilizam agrotóxicos proibidos.
    -> As informações de nível 1 todos podem ter acesso.
    -> As informações de nível 2 apenas diretores ( e o ministro) tem acesso
    -> As informações de nível 3 somente sao acessadas pelo ministro do meio ambiente

O que estou pensando em fazer:
    -> Entrou no "site"
    -> Leu o QR Code
    -> Pegarei a data do qr code
    -> vou dar um decode pelo php
    -> gerar o json
    -> pegar os dados pelo json (nome, cpf, nivel de acesso)
    -> verificar no banco de dados
    -> abrir as pastas que a pessoa tem acesso

    -> Utilizar o token jwt para gerar as hashs (tokens) para assim, gerar o qr code a partir da ferramenta do google
    -> https://developers.google.com/chart/infographics/docs/qr_codes
    -> https://chart.googleapis.com/chart?cht=qr&chs=500x500&chl=token
    -> E então utilizar uma ferramenta em javascript que leia o qr code e leia o token jwt com os dados:

**Comment by danielalexsander** [comment]
Não precisa ser exatamente com php e afins, foi só o que veio na cabeça na hora
-> Pegarei a data do qr code (com data quero dizer os dados)

Mas foi mais ou menos essa ideia que eu tive, a parte do token pode ser diferente, nao sei. Mas a ideia era gerar um qr code pra cada nivel de acesso e ler a imagem do qr code com alguma biblioteca.
